### ISSUE TITLE
Chrome Web Store points to a BAD site

### ISSUE THREAD

**Issue by AnthonyMastrean** [glee/glee#264]
The [gleeBox page on the Chrome Web Store](https://chrome.google.com/webstore/detail/gleebox/miinkdcjglbkbanpkghnkgkgbamdkgji) still points to the old (?) website, which now appears to be taken over by some kind of scam or something: http://thegleebox.com/

**Comment by rogeralmeida** [comment]
Now the chrome webstore is returning `404`
